# Generated by Django 5.1.3 on 2024-12-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='job',
        ),
    ]
